-- Add urine-related markers for staged health UI rollout
ALTER TYPE "LabMarkerType" ADD VALUE IF NOT EXISTS 'URINE_GLUCOSE';
ALTER TYPE "LabMarkerType" ADD VALUE IF NOT EXISTS 'URINE_KETONE';
ALTER TYPE "LabMarkerType" ADD VALUE IF NOT EXISTS 'USG';
ALTER TYPE "LabMarkerType" ADD VALUE IF NOT EXISTS 'URINE_PROTEIN';
ALTER TYPE "LabMarkerType" ADD VALUE IF NOT EXISTS 'UPCR';
